<!-- we write the whole code which we want to execute and catch will catch the error in code -->
<!-- Axios is an libarary which hep us to call apis but in this we dont have to manually handle the error bcoz if response is unsuccessful it automatically throws the error on behalf is us but here fetch doesnt throw error automatically so we have to manually throw the error.   -->
<!-- <script>
    try{
        console.log("Inside try block");
        throw new Error("Failed");   //Error here is an object
    }
    catch(error){
        console.log(error.message);
    }
</script> -->



<!-- in this code we used async function with await keyword and also try and catch for error but this one is with right api link means no error -->
<script>
    async function getTodoItem() {
        try{
        const response = await fetch("https://jsonplaceholder.typicode.com/todos/1");
        // console.log(response);            //response is an obejct which shows us many prperties out of which ok: states if the request is okay that we did in fetch by link as we asked somehting in the link we did a request if its true then its okay else its false and status: as status has differnet no.s which states different stataus like it passed(200) or error(404) as 404 means nothing to retutrn as not found 
        
        
        //there is an error
        if(!response.ok){
            const message = `An error has occurred : ${response.status}`;
            throw new Error(message);
        }

        const data = await response.json();
        console.log(data);
    }
    catch(error){                    //errror in an object so if only want message then use error.message
        console.log(error.message);
    }
    
    }

    getTodoItem();
</script>



<!-- in this code we used async function with await keyword and also try and catch for error and this one is with incorrect api link means error will be there. code by sir-->
<script>
    async function getTodoItem() {
    try {
      const response = await fetch(
        "https://jsonplaceholder.typicode.com/incorrect/1"
      );
  
      // response.ok -> true -> successful
      // response.ok -> false -> unsuccessful
  
      // If an error occurred
      if (!response.ok) {
        throw new Error(`An error occured with status code : ${response.status}`);
      }
  
      const data = await response.json();
      console.log(data);
    } catch (error) {
      console.log(error.message);
    }
  }
  
  getTodoItem();
</script>